name: Build, Test, Package & Release

on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  # Stage 1: Build & Test (Ubuntu only)
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 24
      uses: actions/setup-java@v4
      with:
        java-version: 24
        distribution: 'temurin'
        
    - name: Verify Java version
      run: |
        java -version
        JAVA_VERSION=$(java -version 2>&1 | head -n 1 | cut -d'"' -f2 | cut -d'.' -f1)
        if [ "$JAVA_VERSION" -lt 24 ]; then
          echo "⚠️  WARNING: Using Java $JAVA_VERSION. This project requires Java 24+ for optimal performance."
          echo "⚠️  Some features may not work correctly with older Java versions."
        else
          echo "✅ Using Java $JAVA_VERSION (latest stable)"
        fi
      shell: bash
      
    - name: Set up GraalVM
      uses: graalvm/setup-graalvm@v1
      with:
        java-version: 24
        distribution: oracle
        components: native-image
        
    - name: Install jpackage dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y fakeroot dpkg-dev
        
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          ~/.gradle/daemon
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-m2-
          
    - name: Cache GraalVM
      uses: actions/cache@v4
      with:
        path: |
          ~/.graalvm
          ~/.gradle/caches/modules-2/files-2.1/org.graalvm.nativeimage
        key: ${{ runner.os }}-graalvm-24
        restore-keys: |
          ${{ runner.os }}-graalvm-
          
    - name: Make gradlew executable
      run: chmod +x ./gradlew
      
    - name: Run tests
      run: ./gradlew test
      shell: bash
      
    - name: Build all modules
      run: ./gradlew build
      shell: bash
      
    - name: Test CLI application
      run: ./gradlew :cli:run
      shell: bash
      
    - name: Test module dependency detection
      run: ./gradlew detectModuleDependencies
      shell: bash
      
    - name: Test native image compilation (CLI and Service)
      run: ./gradlew :cli:nativeCompile :service:nativeCompile
      shell: bash
      continue-on-error: true
      
    - name: Test jlink image creation
      run: ./gradlew createAllJlinkImages
      shell: bash
      
    - name: Test packaging (Linux)
      run: |
        echo "🐧 Testing Linux packaging..."
        ./gradlew packageLinux --stacktrace --info
      shell: bash
      continue-on-error: true
      
    - name: Generate reports
      run: ./gradlew distributionReport moduleAnalysisReport
      shell: bash
      
    - name: Upload test artifacts
      uses: actions/upload-artifact@v4
      with:
        name: test-artifacts-ubuntu
        path: |
          build/reports/
          build/distribution-report.md
          build/module-analysis-report.md
        retention-days: 3

  # Stage 2: Package macOS (Parallel)
  package-macos:
    runs-on: macos-latest
    needs: build-and-test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 24
      uses: actions/setup-java@v4
      with:
        java-version: 24
        distribution: 'temurin'
        
    - name: Verify Java version
      run: |
        java -version
        JAVA_VERSION=$(java -version 2>&1 | head -n 1 | cut -d'"' -f2 | cut -d'.' -f1)
        if [ "$JAVA_VERSION" -lt 24 ]; then
          echo "⚠️  WARNING: Using Java $JAVA_VERSION. This project requires Java 24+ for optimal performance."
          echo "⚠️  Some features may not work correctly with older Java versions."
        else
          echo "✅ Using Java $JAVA_VERSION (latest stable)"
        fi
      shell: bash
      
    - name: Set up GraalVM
      uses: graalvm/setup-graalvm@v1
      with:
        java-version: 24
        distribution: oracle
        components: native-image
        
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          ~/.gradle/daemon
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-m2-
          
    - name: Cache GraalVM
      uses: actions/cache@v4
      with:
        path: |
          ~/.graalvm
          ~/.gradle/caches/modules-2/files-2.1/org.graalvm.nativeimage
        key: ${{ runner.os }}-graalvm-24
        restore-keys: |
          ${{ runner.os }}-graalvm-
          
    - name: Make gradlew executable
      run: chmod +x ./gradlew
      
    - name: Build all modules
      run: ./gradlew build
      shell: bash
      
    - name: Generate module dependencies
      run: ./gradlew detectModuleDependencies
      shell: bash
      
    - name: Build native images (CLI and Service)
      run: ./gradlew :cli:nativeCompile :service:nativeCompile
      shell: bash
      continue-on-error: true
      
    - name: Create jlink images
      run: ./gradlew createAllJlinkImages
      shell: bash
      
    - name: Package macOS applications
      run: |
        echo "🍎 Packaging macOS applications..."
        ./gradlew packageMac --stacktrace --info
      shell: bash
      continue-on-error: true
      
    - name: Upload macOS artifacts
      uses: actions/upload-artifact@v4
      with:
        name: macos-artifacts
        path: |
          build/jpackage/
          cli/build/jpackage/
          service/build/jpackage/
          desktop/build/jpackage/
          service-desktop/build/jpackage/
        retention-days: 3

  # Stage 2: Package Windows (Parallel)
  package-windows:
    runs-on: windows-latest
    needs: build-and-test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 24
      uses: actions/setup-java@v4
      with:
        java-version: 24
        distribution: 'temurin'
        
    - name: Verify Java version
      run: |
        java -version
        $JAVA_VERSION = (java -version 2>&1 | Select-String -Pattern 'version "(\d+)' | ForEach-Object { $_.Matches[0].Groups[1].Value })
        if ([int]$JAVA_VERSION -lt 24) {
          Write-Host "⚠️  WARNING: Using Java $JAVA_VERSION. This project requires Java 24+ for optimal performance."
          Write-Host "⚠️  Some features may not work correctly with older Java versions."
        } else {
          Write-Host "✅ Using Java $JAVA_VERSION (latest stable)"
        }
      shell: powershell
      
    - name: Set up GraalVM
      uses: graalvm/setup-graalvm@v1
      with:
        java-version: 24
        distribution: oracle
        components: native-image
        
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          ~/.gradle/daemon
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-m2-
          
    - name: Cache GraalVM
      uses: actions/cache@v4
      with:
        path: |
          ~/.graalvm
          ~/.gradle/caches/modules-2/files-2.1/org.graalvm.nativeimage
        key: ${{ runner.os }}-graalvm-24
        restore-keys: |
          ${{ runner.os }}-graalvm-
          
    - name: Build all modules
      run: .\gradlew.bat build
      shell: cmd
      
    - name: Generate module dependencies
      run: .\gradlew.bat detectModuleDependencies
      shell: cmd
      
    - name: Build native images (CLI and Service)
      run: .\gradlew.bat :cli:nativeCompile :service:nativeCompile
      shell: cmd
      continue-on-error: true
      
    - name: Create jlink images
      run: .\gradlew.bat createAllJlinkImages
      shell: cmd
      
    - name: Package Windows applications
      run: |
        echo "🪟 Packaging Windows applications..."
        .\gradlew.bat packageWindows --stacktrace --info
      shell: cmd
      continue-on-error: true
      
    - name: Upload Windows artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-artifacts
        path: |
          build/jpackage/
          cli/build/jpackage/
          service/build/jpackage/
          desktop/build/jpackage/
          service-desktop/build/jpackage/
        retention-days: 3

  # Stage 2: Package Linux (Parallel)
  package-linux:
    runs-on: ubuntu-latest
    needs: build-and-test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 24
      uses: actions/setup-java@v4
      with:
        java-version: 24
        distribution: 'temurin'
        
    - name: Verify Java version
      run: |
        java -version
        JAVA_VERSION=$(java -version 2>&1 | head -n 1 | cut -d'"' -f2 | cut -d'.' -f1)
        if [ "$JAVA_VERSION" -lt 24 ]; then
          echo "⚠️  WARNING: Using Java $JAVA_VERSION. This project requires Java 24+ for optimal performance."
          echo "⚠️  Some features may not work correctly with older Java versions."
        else
          echo "✅ Using Java $JAVA_VERSION (latest stable)"
        fi
      shell: bash
      
    - name: Set up GraalVM
      uses: graalvm/setup-graalvm@v1
      with:
        java-version: 24
        distribution: oracle
        components: native-image
        
    - name: Install jpackage dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y fakeroot dpkg-dev
        
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          ~/.gradle/daemon
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-m2-
          
    - name: Cache GraalVM
      uses: actions/cache@v4
      with:
        path: |
          ~/.graalvm
          ~/.gradle/caches/modules-2/files-2.1/org.graalvm.nativeimage
        key: ${{ runner.os }}-graalvm-24
        restore-keys: |
          ${{ runner.os }}-graalvm-
          
    - name: Make gradlew executable
      run: chmod +x ./gradlew
      
    - name: Build all modules
      run: ./gradlew build
      shell: bash
      
    - name: Generate module dependencies
      run: ./gradlew detectModuleDependencies
      shell: bash
      
    - name: Build native images (CLI and Service)
      run: ./gradlew :cli:nativeCompile :service:nativeCompile
      shell: bash
      continue-on-error: true
      
    - name: Create jlink images
      run: ./gradlew createAllJlinkImages
      shell: bash
      
    - name: Package Linux applications
      run: |
        echo "🐧 Packaging Linux applications..."
        ./gradlew packageLinux --stacktrace --info
      shell: bash
      continue-on-error: true
      
    - name: Upload Linux artifacts
      uses: actions/upload-artifact@v4
      with:
        name: linux-artifacts
        path: |
          build/jpackage/
          cli/build/jpackage/
          service/build/jpackage/
          desktop/build/jpackage/
          service-desktop/build/jpackage/
        retention-days: 3

  # Stage 3: Create Release (Only if all OS succeed + main branch/release)
  create-release:
    runs-on: ubuntu-latest
    needs: [package-macos, package-windows, package-linux]
    if: |
      (github.ref == 'refs/heads/main' || github.event_name == 'release') &&
      needs.package-macos.result == 'success' &&
      needs.package-windows.result == 'success' &&
      needs.package-linux.result == 'success'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Cache artifacts
      uses: actions/cache@v4
      with:
        path: ./artifacts
        key: ${{ runner.os }}-artifacts-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-artifacts-
          
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./artifacts
        
    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v1.0.0
        name: Release v1.0.0
        draft: false
        prerelease: false
        files: |
          artifacts/macos-artifacts/*
          artifacts/windows-artifacts/*
          artifacts/linux-artifacts/*
        body: |
          ## System Test Suite Release
          
          This release contains native applications for all platforms:
          
          ### 📦 Downloads
          - **macOS**: `.dmg` installer with native app
          - **Windows**: `.msi` installer with native app  
          - **Linux**: `.deb` package with native app
          
          ### 🚀 Features
          - CLI application with native executable
          - Desktop GUI application with native installer
          - Web service with native executable
          - Service-desktop app with browser integration
          
          ### 📋 Installation
          1. Download the appropriate package for your platform
          2. Install using the standard installer
          3. Run the application from your applications menu
          
          ### 🔧 Development
          - Built with Java 24 and Oracle GraalVM 24
          - Native images for optimal performance
          - Cross-platform compatibility
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Stage 3: Upload Individual Artifacts (Even if some OS fail)
  upload-individual-artifacts:
    runs-on: ubuntu-latest
    needs: [package-macos, package-windows, package-linux]
    if: always()
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Download macOS artifacts
      if: needs.package-macos.result == 'success'
      uses: actions/download-artifact@v4
      with:
        name: macos-artifacts
        path: ./macos-artifacts
        
    - name: Download Windows artifacts
      if: needs.package-windows.result == 'success'
      uses: actions/download-artifact@v4
      with:
        name: windows-artifacts
        path: ./windows-artifacts
        
    - name: Download Linux artifacts
      if: needs.package-linux.result == 'success'
      uses: actions/download-artifact@v4
      with:
        name: linux-artifacts
        path: ./linux-artifacts
        
    - name: Upload individual artifacts summary
      uses: actions/upload-artifact@v4
      with:
        name: individual-artifacts-summary
        path: |
          macos-artifacts/
          windows-artifacts/
          linux-artifacts/
        retention-days: 3
