name: Package macOS Applications

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  package-macos:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 24
      uses: actions/setup-java@v4
      with:
        java-version: 24
        distribution: 'temurin'
        
    - name: Verify Java version
      run: |
        java -version
        JAVA_VERSION=$(java -version 2>&1 | head -n 1 | cut -d'"' -f2 | cut -d'.' -f1)
        if [ "$JAVA_VERSION" -lt 24 ]; then
          echo "⚠️  WARNING: Using Java $JAVA_VERSION. This project requires Java 24+ for optimal performance."
          echo "⚠️  Some features may not work correctly with older Java versions."
        else
          echo "✅ Using Java $JAVA_VERSION (latest stable)"
        fi
      shell: bash
      
    - name: Set up GraalVM
      uses: graalvm/setup-graalvm@v1
      with:
        java-version: 24
        distribution: graalvm
        components: native-image
        
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Make gradlew executable
      run: chmod +x ./gradlew
      
    - name: Build all modules
      run: ./gradlew build
      shell: bash
      
    - name: Generate module dependencies
      run: ./gradlew detectModuleDependencies
      shell: bash
      
    - name: Build native images (CLI and Service)
      run: ./gradlew :cli:nativeCompile :service:nativeCompile
      shell: bash
      continue-on-error: true
      
    - name: Create jlink images
      run: ./gradlew createAllJlinkImages
      shell: bash
      
    - name: Package macOS applications
      run: |
        echo "🍎 Packaging macOS applications..."
        ./gradlew packageMac --stacktrace --info
      shell: bash
      continue-on-error: true
      
    - name: Generate distribution report
      run: ./gradlew distributionReport
      shell: bash
      
    - name: Upload macOS artifacts
      uses: actions/upload-artifact@v4
      with:
        name: macos-artifacts
        path: |
          build/jpackage/
          cli/build/jpackage/
          service/build/jpackage/
          desktop/build/jpackage/
          service-desktop/build/jpackage/
        retention-days: 30
