name: Test and Build

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 24
      uses: actions/setup-java@v4
      with:
        java-version: 24
        distribution: 'temurin'
        
    - name: Verify Java version
      run: |
        java -version
        JAVA_VERSION=$(java -version 2>&1 | head -n 1 | cut -d'"' -f2 | cut -d'.' -f1)
        if [ "$JAVA_VERSION" -lt 24 ]; then
          echo "⚠️  WARNING: Using Java $JAVA_VERSION. This project requires Java 24+ for optimal performance."
          echo "⚠️  Some features may not work correctly with older Java versions."
        else
          echo "✅ Using Java $JAVA_VERSION (latest stable)"
        fi
      shell: bash
      
    - name: Set up GraalVM
      uses: graalvm/setup-graalvm@v1
      with:
        java-version: 24
        distribution: oracle
        components: native-image
        
    - name: Install jpackage dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y fakeroot dpkg-dev
        
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          ~/.gradle/daemon
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-m2-
          
    - name: Cache GraalVM
      uses: actions/cache@v4
      with:
        path: |
          ~/.graalvm
          ~/.gradle/caches/modules-2/files-2.1/org.graalvm.nativeimage
        key: ${{ runner.os }}-graalvm-24
        restore-keys: |
          ${{ runner.os }}-graalvm-
          
    - name: Make gradlew executable
      run: chmod +x ./gradlew
      
    - name: Run tests
      run: ./gradlew test
      shell: bash
      
    - name: Build all modules
      run: ./gradlew build
      shell: bash
      
    - name: Test CLI application
      run: ./gradlew :cli:run
      shell: bash
      
    - name: Test module dependency detection
      run: ./gradlew detectModuleDependencies
      shell: bash
      
    - name: Test native image compilation (CLI and Service)
      run: ./gradlew :cli:nativeCompile :service:nativeCompile
      shell: bash
      continue-on-error: true
      
    - name: Test jlink image creation
      run: ./gradlew createAllJlinkImages
      shell: bash
      
    - name: Test packaging (Linux)
      run: |
        echo "🐧 Testing Linux packaging..."
        ./gradlew packageLinux --stacktrace --info
      shell: bash
      continue-on-error: true
      
    - name: Generate reports
      run: ./gradlew distributionReport moduleAnalysisReport
      shell: bash
      
    - name: Upload test artifacts
      uses: actions/upload-artifact@v4
      with:
        name: test-artifacts-ubuntu
        path: |
          build/reports/
          build/distribution-report.md
          build/module-analysis-report.md
        retention-days: 7
